package com.careerforge.entity.enums;

public enum AuditEventType {
    USER_STATUS_UPDATED,
    USER_SELF_DISABLE_REJECTED,
    COMPANY_VERIFICATION_UPDATED,
    JOB_MODERATION_PERFORMED,
    JOB_PUBLISH_GUARD_BLOCKED,
    JOB_DELETED,
    ADMIN_LOGIN_SUCCESS,
    ADMIN_LOGIN_FAILURE
}
