package com.careerforge.entity.enums;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_UPDATED,
    APPLICATION_UPDATE, // Retained for backward compatibility
    APPLICATION_SHORTLISTED,
    APPLICATION_REJECTED,
    APPLICATION_ACCEPTED,
    INTERVIEW_INVITE,
    INTERVIEW_RESCHEDULED,
    COMPANY_VERIFICATION_PENDING,
    COMPANY_VERIFICATION_REJECTED,
    COMPANY_VERIFIED,
    JOB_POSTING_CLOSED,
    JOB_POSTING_DRAFTED,
    JOB_POSTING_ARCHIVED,
    JOB_POSTING_PUBLISHED,
    ACCOUNT_DISABLED,
    SYSTEM_ALERT,
    JOB_RECOMMENDATION
}
