import { type ClassValue, clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatCurrency(amount?: number, currency = 'INR'): string {
  if (amount === undefined || amount === null) return 'N/A';
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function parseDate(dateString?: string): Date | null {
  if (!dateString) return null;
  const normalized = dateString.trim();

  // Date-only format (YYYY-MM-DD): parse with local year, month, day to prevent timezone day shift
  if (!normalized.includes('T') && /^\d{4}-\d{2}-\d{2}$/.test(normalized)) {
    const parts = normalized.split('-').map(Number);
    if (parts.length === 3) {
      const d = new Date(parts[0], parts[1] - 1, parts[2]);
      return isNaN(d.getTime()) ? null : d;
    }
  }

  // If the ISO timestamp has time ('T') but no timezone specifier ('Z' or offset like +05:30),
  // it was generated by the backend in UTC. Treat it as UTC by appending 'Z'.
  let isoString = normalized;
  if (isoString.includes('T') && !isoString.endsWith('Z') && !/[+-]\d{2}:\d{2}$/.test(isoString)) {
    isoString = `${isoString}Z`;
  }
  const date = new Date(isoString);
  return isNaN(date.getTime()) ? null : date;
}

export function formatDate(dateString?: string, timeZone?: string): string {
  if (!dateString) return 'N/A';
  const normalized = dateString.trim();

  // Pure calendar date format (YYYY-MM-DD): format directly to prevent cross-timezone day shift
  if (!normalized.includes('T') && /^\d{4}-\d{2}-\d{2}$/.test(normalized)) {
    const parts = normalized.split('-').map(Number);
    if (parts.length === 3) {
      const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
      return `${months[parts[1] - 1]} ${parts[2]}, ${parts[0]}`;
    }
  }

  try {
    const date = parseDate(dateString);
    if (!date) return dateString;
    return new Intl.DateTimeFormat('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      timeZone: timeZone || undefined,
    }).format(date);
  } catch {
    return dateString;
  }
}

export function formatDateTime(dateString?: string, timeZone?: string): string {
  if (!dateString) return 'N/A';
  try {
    const date = parseDate(dateString);
    if (!date) return dateString;
    return new Intl.DateTimeFormat('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: true,
      timeZone: timeZone || undefined,
    }).format(date);
  } catch {
    return dateString;
  }
}

export function formatForDateTimeLocal(dateString?: string): string {
  if (!dateString) return '';
  const date = parseDate(dateString);
  if (!date) return '';
  const pad = (n: number) => n.toString().padStart(2, '0');
  const year = date.getFullYear();
  const month = pad(date.getMonth() + 1);
  const day = pad(date.getDate());
  const hours = pad(date.getHours());
  const minutes = pad(date.getMinutes());
  return `${year}-${month}-${day}T${hours}:${minutes}`;
}

export function formatPercentage(val?: number): string {
  if (val === undefined || val === null || isNaN(val)) return '0%';
  return `${val.toFixed(1)}%`;
}

export function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

export function getErrorMessage(
  error: unknown,
  defaultMessage = 'An unexpected error occurred. Please try again.'
): string {
  if (!error) return defaultMessage;
  const err = error as any;
  if (!err.response) {
    if (err.message === 'Network Error' || err.code === 'ERR_NETWORK') {
      return 'Unable to connect to CareerForge. Please check your connection.';
    }
    return err.message || defaultMessage;
  }
  const status = err.response.status;
  const data = err.response.data;

  // Use explicit backend message if safe and available
  if (
    data?.message &&
    typeof data.message === 'string' &&
    !data.message.includes('Exception') &&
    !data.message.includes('SQL') &&
    !data.message.includes('Internal')
  ) {
    return data.message;
  }

  switch (status) {
    case 401:
      return 'Your session has expired. Please sign in again.';
    case 403:
      if (data?.code === 'ACCOUNT_DISABLED') {
        return 'Your account has been disabled by an administrator. Please contact support for assistance.';
      }
      return 'You do not have permission to perform this action.';
    case 404:
      return 'The requested resource could not be found.';
    case 409:
      return 'Your request conflicts with the current data. Please refresh and try again.';
    case 422:
      return 'Some of the information provided is invalid. Please check and try again.';
    case 429:
      return 'Too many requests. Please wait a moment and try again.';
    case 500:
      return 'Something went wrong on the server. Please try again later.';
    case 502:
      return 'The server is temporarily unavailable. Please try again shortly.';
    case 503:
      return 'The service is temporarily unavailable.';
    case 504:
      return 'The server took too long to respond. Please try again.';
    default:
      return defaultMessage;
  }
}
